### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' in position 22: ordinal not in range(128)

### ISSUE THREAD

**Issue by blucap** [makkoncept/pyvoc#2]
After install, I get this error:

```
(python3) Sun Jan 13 15:18:52 [Mint] user [~] $ pyvoc word
 |

word 
Verb:            express something spoken or written
example:         he words his request in a particularly ironic way

Noun:            single meaningful element of speech or writing
example:         Traceback (most recent call last):
  File "/home/user/anaconda2/envs/python3/bin/pyvoc", line 11, in <module>
    sys.exit(main())
  File "/home/user/anaconda2/envs/python3/lib/python3.5/site-packages/pyvoc/pyvoc.py", line 160, in main
    parsed_response = dictionary(args.word)
  File "/home/user/anaconda2/envs/python3/lib/python3.5/site-packages/pyvoc/pyvoc.py", line 103, in dictionary
    pretty_print_definition(word, parsed_response, examples)
  File "/home/user/anaconda2/envs/python3/lib/python3.5/site-packages/pyvoc/pyvoc.py", line 68, in pretty_print_definition
    print(sentence)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' in position 22: ordinal not in range(128)
```

**Comment by makkoncept** [comment]
hey @blucap, thanks for pointing out this bug. 
It will be solved in the new version.
