### ISSUE TITLE
pyvoc verbs

### ISSUE THREAD

**Issue by OrionRandD** [makkoncept/pyvoc#4]
Is that possible to add a conjugation verb feature?
Like showing the verbs tenses - and conjugation?
Because in the case of verbs the actual features are very simple.
It is not really a issue, but a feature request...

**Comment by makkoncept** [comment]
Hey @OrionRandD, I am sorry for replying so late, i forgot to turn on my mail notifications.

This is a good feature request but I have looked at the Oxford API and could not find the support for it. I will look at other APIs and would try to work it out but I am not sure as there are not so many good free dictionary APIs out there.

**Comment by OrionRandD** [comment]
Hey,

This function used to work.
I have that in my ".bashrc",
But, does not work anymore :(

# configuration <
https://unix.stackexchange.com/questions/42320/is-there-a-standard-unix-command-to-check-english-verb
-conjugation >
# source < http://conjugator.reverso.net/conjugation-english.html >
# Função para conjugar verbos em Inglês

function verbtense () {
    wget -qO -
http://conjugator.reverso.net/conjugation-english-verb-$1.html | \
    sed -n "/>Preterite\|>Past</{s@<[^>]*>@ @g;s/\s\+/ /g;/e I/s/.* I \([^
]*\) you .*/Simple past: \1/;/ Past/s/ Past /Past participle: /;p}" ;
}


Em qua, 23 de jan de 2019 às 02:03, Mayank Nader <notifications@github.com>
escreveu:

**Comment by YiHoze** [comment]
Initialization seems to fail. The error messages are below:

 |Creating necessary config files
 -getting api keys. please handle with care!
 |Traceback (most recent call last):
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\yihoze\AppData\Local\Programs\Python\Python38\Scripts\pyvoc.exe\__main__.py", line 7, in <module>
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\site-packages\pyvoc\pyvoc.py", line 181, in main
    parsed_response = dictionary(args.word)
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\site-packages\pyvoc\pyvoc.py", line 94, in dictionary
    check_config_dir()
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\site-packages\pyvoc\check_config.py", line 66, in check_config_dir
    create_config_file()
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\site-packages\pyvoc\check_config.py", line 75, in create_config_file
    config["API"] = {"app_id": app_id, "app_key": app_key}
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\configparser.py", line 974, in __setitem__
    self.read_dict({key: value})
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\configparser.py", line 754, in read_dict
    self.set(section, key, value)
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\configparser.py", line 1200, in set
    self._validate_value_types(option=option, value=value)
  File "c:\users\yihoze\appdata\local\programs\python\python38\lib\configparser.py", line 1185, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings

**Comment by makkoncept** [comment]
<img width="822" alt="paint" src="https://user-images.githubusercontent.com/34679965/105613591-76fd3180-5de9-11eb-9d5e-be591a81dba4.png">
<img width="822" alt="paint" src="https://user-images.githubusercontent.com/34679965/105613599-7f556c80-5de9-11eb-9eb0-e8eb2f95483f.png">

**Comment by makkoncept** [comment]
should be working with the new release
